services:
  rese-nginx:
    image: nginx:1.21.1
    expose:
      - "80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php

  front-nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/front-nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rese-nginx

  php:
    build: ./docker/php
    user: "1000:1000"
    volumes:
      - ./src:/var/www/
    depends_on:
      - mysql
    environment:
      - QUEUE_CONNECTION=database # キューの接続方法を指定
    command: php-fpm

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8080:80"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - "./bin/mhsendmail:/usr/local/bin/mhsendmail"
      - maildir:/tmp

  supervisor:
    build: ./docker/supervisor
    volumes:
      - ./src:/var/www/
    depends_on:
      - php
    command:
      ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

volumes:
  maildir:
